#!/usr/bin/env bash
seconds=$(awk '{ print $1 }' < /proc/uptime)

d=$(echo "$seconds / 3600 / 24" | bc) 
h=$(echo "$seconds / 3600 % 24" | bc)
m=$(echo "$seconds / 60 % 60" | bc)

uptime="0m"

if [[ $d != 0 ]]; then
  uptime="${d}d "
fi

if [[ $h != 0 ]]; then
  uptime="${uptime}${h}h "
fi

if [[ $m != 0 ]]; then
  uptime="${uptime}${m}m "
fi

echo "$uptime"