#!/usr/bin/env bash
seconds=$(awk '{ print $1 }' < /proc/uptime)

# Calculate days, hours, and minutes
d=$(echo "$seconds / 3600 / 24" | bc) 
h=$(echo "$seconds / 3600 % 24" | bc)
m=$(echo "$seconds / 60 % 60" | bc)

uptime=""
if [[ $d != 0 ]]; then
  uptime="${d}d "
fi

if [[ $h != 0 ]]; then
  uptime="${uptime}${h}h "
fi

if [[ $m != 0 ]]; then
  uptime="${uptime}${m}m "
fi

# Default to 0m if there's no uptime yet
uptime="${uptime:-0m}"
# Trim any trailing whitespace
echo "${uptime%% }"